### ISSUE TITLE
Test-case failing with version @next

### ISSUE THREAD

**Issue by veeramarni** [cdmbase/fullstack-pro#10]
To replicate the issue just run `npm run test` from `root` folder. 
```
  ● redux integration › updates child props on state change
    expect(received).toEqual(expected)
    Expected value to equal:
      {"people": [{"name": "Leia Skywalker"}]}
    Received:
      {"people": [{"name": "Leia Skywalker", Symbol(id): "$ROOT_QUERY.allPeople({\"first\":2}).people.0"}], Symbol(i
d): "$ROOT_QUERY.allPeople({\"first\":2})"}

    Difference:

    - Expected
    + Received

      Object {
        "people": Array [
          Object {
            "name": "Leia Skywalker",
    +       Symbol(id): "$ROOT_QUERY.allPeople({\"first\":2}).people.0",
          },
        ],
    +   Symbol(id): "$ROOT_QUERY.allPeople({\"first\":2})",
      }

      at Component.componentWillReceiveProps (packages/sample-client-react/src/containers/__tests__/redux.test.tsx:65:54)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:610:23
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at ReactCompositeComponentWrapper.updateComponent (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:609:9)
      at ReactCompositeComponentWrapper.receiveComponent (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:546:10)
      at Object.receiveComponent (node_modules/react-test-renderer/lib/ReactReconciler.js:124:22)
      at ReactCompositeComponentWrapper._updateRenderedComponent (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:753:23)
      at ReactCompositeComponentWrapper._performComponentUpdate (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:723:10)
      at ReactCompositeComponentWrapper.updateComponent (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:644:12)
      at ReactCompositeComponentWrapper.receiveComponent (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:546:10)
```

**Comment by veeramarni** [comment]
Few other tests fails as well. 
```
Test Suites: 3 failed, 4 passed, 7 of 8 total
Tests:       4 failed, 18 passed, 22 total
Snapshots:   1 failed, 1 total
```

**Comment by veeramarni** [comment]
not relevant anymore
