### ISSUE TITLE
token not fount error 

### ISSUE THREAD

**Issue by veeramarni** [cdmbase/fullstack-pro#16]
Throw token not found error in better way

currently it throws like this

```
./token_revoke.sh eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJkOWMyMmE2Mi1kNDk3LTQyMWQtYWJhOC0zOWRiYjMxOWQyMmEiLCJzdWIiOiI1OWQ4MDYzZDk0OWQ3NTcxNjI0YWE0MDQiLCJleHAiOjE1MDc5MTA3NTIsImlhdCI6MTUwNzkwNzE1Mn0.Z5rmbWgeumapgvP2Zglg6dKqJA6VBl-9KFxbSwE7SnY
{}Veeras-MacBook-Pro:curl veeramarni$ ./tokeinfo.sh eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJkOWMyMmE2Mi1kNDk3LTQyMWQtYWJhOC0zOWRiYjMxOWQyMmEiLCJzdWIiOiI1OWQ4MDYzZDk0OWQ3NTcxNjI0YWE0MDQiLCJleHAiOjE1MDc5MTA3NTIsImlhdCI6MTUwNzkwNzE1Mn0.Z5rmbWgeumapgvP2Zglg6dKqJA6VBl-9KFxbSwE7SnY<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJkOWMyMmE2Mi1kNDk3LTQyMWQtYWJhOC0zOWRiYjMxOWQyMmEiLCJzdWIiOiI1OWQ4MDYzZDk0OWQ3NTcxNjI0YWE0MDQiLCJleHAiOjE1MDc5MTA3NTIsImlhdCI6MTUwNzkwNzE1Mn0.Z5rmbWgeumapgvP2Zglg6dKqJA6VBl-9KFxbSwE7SnY not Found or not Valid<br> &nbsp; &nbsp;at ValidateTokenService.&lt;anonymous&gt; (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/IDE/identity-stack/servers/packages/identity-server-core/lib/index.js:3128:1)<br> &nbsp; &nbsp;at Generator.next (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at fulfilled (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/IDE/identity-stack/servers/packages/identity-server-core/lib/index.js:2995:1)<br> &nbsp; &nbsp;at &lt;anonymous&gt;<br> &nbsp; &nbsp;at process._tickCallback (internal/process/next_tick.js:188:7)</pre>
</body>
</html>
```

**Comment by veeramarni** [comment]
Wrong one
