### ISSUE TITLE
generate persistgraphql

### ISSUE THREAD

**Issue by veeramarni** [cdmbase/fullstack-pro#17]
Right now `persistgraphql` work on generating `extracted_queries.json`. Need to find ways to gather all the `grahql` and create `extracted-queries.json` which is accessible from frontend and backend.

**Comment by veeramarni** [comment]
Right now fails with
```
"Error: Must provide a query.
    at SubscriptionClient.vendor../node_modules/subscriptions-transport-ws/dist/client.js.SubscriptionClient.checkOperationOptions (http://localhost:3000/bundle.fbccb8380150e8fe6690.js:416487:19)
    at http://localhost:3000/bundle.fbccb8380150e8fe6690.js:416430:19
    at <anonymous>"
```

**Comment by veeramarni** [comment]
With apollo-server it can be automated.
