### ISSUE TITLE
graphql errors

### ISSUE THREAD

**Issue by veeramarni** [cdmbase/fullstack-pro#18]
Noticing some errors. 

```
[16:13:06.790Z] ERROR @sample-stack-server: 2 errors were thrown when executing your GraphQL queries.
    Error: 2 errors were thrown when executing your GraphQL queries.
        at /Users/veeramarni/Documents/fullstack-pro/node_modules/react-apollo/server.js:86:19
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
[HPM] Error occurred while trying to proxy request / from localhost:3000 to http://localhost:3010 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

**Comment by veeramarni** [comment]
Those errors occur when the server not reachable to `graphql server` when doing SSR. So make sure the `GRAPHQL_SERVER` is up and accessible from the CLIENT_SERVER.
