### ISSUE TITLE
esm webpack build is not getting generated

### ISSUE THREAD

**Issue by veeramarni** [cdmbase/fullstack-pro#295]
1. Our `develop` branch which currently working uses [esm](https://github.com/standard-things/esm). The reason we need to use this [esm wrapper](https://github.com/standard-things/esm#getting-started) is to support nodejs to support esm package with CJS bundle (webpack generated). Webpack for server side won't bundle  node_module packages as we exclude [here[(https://github.com/cdmbase/fullstack-pro/blob/develop/tools/webpack/server.config.js#L132)

2. For nodejs 16 support ESM but with [few restrictions](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c). 

3. So for our test we using this branch

**Comment by veeramarni** [comment]
With all our testing, we getting 


```
$ cross-env NODE_ENV=development ENV_FILE=../../config/development/dev.env node --harmony dist
file:///Users/veeramarni/Documents/development/workspace/projects/common/fullstack-pro/servers/frontend-server/dist/index.js:1560
module.exports = require("@babel/runtime/helpers/interopRequireDefault");
^

ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/Users/veeramarni/Documents/development/workspace/projects/common/fullstack-pro/servers/frontend-server/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
```

**Comment by veeramarni** [comment]
need to test with https://github.com/whoisYeshua/webpack-simple-boilerplate

**Comment by veeramarni** [comment]
webpack-node_externals causing to add  Commonjs `require` https://github.com/liady/webpack-node-externals/issues/110
So we need to add `importType: 'module'`

**Comment by veeramarni** [comment]
The above change help to replace `require`.  Now we getting following error

```

TypeError: _interopRequireDefault is not a function
    at Object.2782 (file:///Users/veeramarni/Documents/development/workspace/projects/common/fullstack-pro/servers/frontend-server/dist/index.js:1360:180)
    at __webpack_require__ (file:///Users/veeramarni/Documents/development/workspace/projects/common/fullstack-pro/servers/frontend-server/dist/index.js:2209:40)
    at file:///Users/veeramarni/Documents/development/workspace/projects/common/fullstack-pro/servers/frontend-server/dist/index.js:2219:1
    at file:///Users/veeramarni/Documents/development/workspace/projects/common/fullstack-pro/servers/frontend-server/dist/index.js:2220:3
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
    at async loadESM (node:internal/process/esm_loader:91:5)

```

**Comment by zakirhossen23** [comment]
In which files are you getting that error?

**Comment by veeramarni** [comment]
We removed `require` everywhere but still, we see that issue. Again the issue can be replicated when you run step 4 in the description above.

**Comment by zakirhossen23** [comment]
You can try, something like this:
`
var package = import("@package/name").default();
`

**Comment by zakirhossen23** [comment]
I was trying to install packages `yarn install` But it was getting stuck at "Network issue".
I have recently faced this issue and solved by using import. If you have any VPS? You can give me, I will try to fix it.

**Comment by zakirhossen23** [comment]
Check this code:
How to use import

https://github.com/zakirhossen23/wave-data-celo/blob/main/wavedata-api/pages/api/GET/getFhir.js

without .mjs
without require
