### ISSUE TITLE
TypeError: Cannot read property 'parentCompilation' of undefined

### ISSUE THREAD

**Issue by veeramarni** [cdmbase/fullstack-pro#42]
With `spinjs": "0.4.159",` we noticing following errors.

```
> full-stack-backend-server@0.0.1 watch /Users/full-stack/servers/backend-server
> cross-env NODE_ENV=development ENV_FILE=../../config/development/dev.env spin watch

TypeError: Cannot read property 'parentCompilation' of undefined
    at Object.getRootCompiler (/Users/full-stack/node_modules/awesome-typescript-loader/src/instance.ts:71:15)
    at compiler (/Users/full-stack/node_modules/awesome-typescript-loader/src/index.ts:40:23)
    at Object.loader (/Users/full-stack/node_modules/awesome-typescript-loader/src/index.ts:14:12)
    at LOADER_EXECUTION (/Users/full-stack/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/full-stack/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Users/full-stack/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at /Users/full-stack/node_modules/loader-runner/lib/LoaderRunner.js:202:4
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3) 'TypeError: Cannot read property \'parentCompilation\' ofundefined\n    at Object.getRootCompiler (/Users/full-stack/node_modules/awesome-typescript-loader/src/instance.ts:71:15)\n    at compiler (/Users/full-stack/node_modules/awesome-typescript-loader/src/index.ts:40:23)\n    at Object.loader (/Users/full-stack/node_modules/awesome-typescript-loader/src/index.ts:14:12)\n    at LOADER_EXECUTION (/Users/full-stack/node_modules/loader-runner/lib/LoaderRunner.js:119:14)\n    at runSyncOrAsync (/Users/full-stack/node_modules/loader-runner/lib/LoaderRunner.js:120:4)\n    at iterateNormalLoaders (/Users/full-stack/node_modules/loader-runner/lib/LoaderRunner.js:229:2)\n    at /Users/full-stack/node_modules/loader-runner/lib/LoaderRunner.js:202:4\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)'
server-webpack error Module build failed (from /Users/full-stack/node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
Cannot read property 'parentCompilation' of undefined

    at Object.getRootCompiler (/Users/full-stack/node_modules/awesome-typescript-loader/src/instance.ts:71:15)
    at compiler (/Users/full-stack/node_modules/awesome-typescript-loader/src/index.ts:40:23)
    at Object.loader (/Users/full-stack/node_modules/awesome-typescript-loader/src/index.ts:14:12)
```

**Comment by veeramarni** [comment]
The issue seems to be from `spinjs` which checks for `thread-loader` package, if it exist then it includes ` { loader: 'thread-loader', options: { workers: 7 }` in the loader which causing this issue.

```
  "haul": "1.0.0-beta.13",
    |-   "thread-loader": 1.1.15

```

From spinjs debug log, we notice the loader loaded.
```
        { test: /^(?!.*[\\\/]node_modules[\\\/]).*\.ts$/,
          use:
           [ { loader: 'thread-loader', options: { workers: 7 } },
             { loader: 'awesome-typescript-loader',
               options: { configFileName: './tsconfig.json', useCache: true } } ] } ],
```

Resolution:
--
remove `haul` package from `package.json` as we not currently using it.

**Comment by veeramarni** [comment]
Further, the issue can be pursued by using ts-loader instead.
https://github.com/webpack-contrib/thread-loader/issues/7
